import type { Metadata } from "next"; // Metadata 타입을 가져옴
import { Inter } from "next/font/google"; // Google 폰트 Inter를 가져옴
import "./globals.css"; // 글로벌 CSS 파일을 가져옴

// Inter 폰트를 설정, 라틴 문자 서브셋을 포함
const inter = Inter({ subsets: ["latin"] });

// 메타데이터 설정
export const metadata: Metadata = {
  title: "Create Next App", // 페이지 타이틀
  description: "Generated by create next app", // 페이지 설명
};

// RootLayout 컴포넌트 정의
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {" "}
      {/* HTML 언어 설정 */}
      <body className={inter.className}>
        {" "}
        {/* Inter 폰트 클래스 적용 */}
        {children} {/* 자식 컴포넌트 렌더링 */}
      </body>
    </html>
  );
}
